apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: srb-middleware-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: srb-middleware
    name: srb-middleware
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: srb-middleware:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/lab-dexter/srb_middleware.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MYSQL_USER
          value: remote-admin
        - name: MYSQL_PASSWORD
          value: Some-pass!23
        - name: MYSQL_DATABASE
          value: smart-recycling-bins
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: a7b7dabc0976e39c
      type: Generic
    - github:
        secret: 3cbe25b31717e695
      type: GitHub
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: srb-middleware
    name: srb-middleware
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/dexter-lab/srb-middleware:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: srb-middleware
    name: srb-middleware
  spec:
    host: srb-middleware-dexter-lab.e4ff.pro-eu-west-1.openshiftapps.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: srb-middleware
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-09-07T20:13:40Z
        status: "True"
        type: Admitted
      host: srb-middleware-dexter-lab.e4ff.pro-eu-west-1.openshiftapps.com
      routerCanonicalHostname: elb.e4ff.pro-eu-west-1.openshiftapps.com
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: srb-middleware
    name: srb-middleware
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: srb-middleware
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: srb-middleware
    name: srb-middleware
  spec:
    replicas: 1
    selector:
      deploymentconfig: srb-middleware
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: srb-middleware
          deploymentconfig: srb-middleware
      spec:
        containers:
        - image: docker-registry.default.svc:5000/dexter-lab/srb-middleware@sha256:1828745d37517912af8c17be3311e605885c7749cc40f086996fab3b58acc978
          imagePullPolicy: Always
          name: srb-middleware
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - srb-middleware
        from:
          kind: ImageStreamTag
          name: srb-middleware:latest
          namespace: dexter-lab
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
